# Mono sandbox adapted for CodeWars
#
# VERSION               0.0.2

FROM      rwentzel/ubuntu-mono
MAINTAINER Jacques Sineriz "ssineriz@gmail.com"

# make sure the package repository is up to date

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list && apt-get update



# install ucspi-tcp for tcpserver and iptables for basic firewalling

RUN apt-get install -y ucspi-tcp

 && apt-get install -y iptables

# get server.sh

ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/server.sh /usr/local/bin/server.sh

# get runcsharp.sh

ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/runcsharp.sh /usr/local/bin/runcsharp.sh



# get ServiceStack.Text.dll
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/lib/ServiceStack.Text.dll /usr/local/lib/mono/4.5/ServiceStack.Text.dll



# get CodeWars.CSharp.TestFramework.dll

# this is the compiled version of https://github.com/edokan/kata-test-framework-csharp (without test units and debug code)

ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/lib/CodeWars.CSharp.TestFramework.dll /usr/local/lib/mono/4.5/CodeWars.CSharp.TestFramework.dll

# all in one script to tackle the 42 layers limit
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/prepare.sh /usr/local/bin/prepare.sh
RUN chmod +x /usr/local/bin/prepare.sh && /usr/local/bin/prepare.sh || return 0 

EXPOSE 7777

# start listener
ENTRYPOINT ["/usr/local/bin/server.sh"]