# Mono sandbox adapted for CodeWars
#
# VERSION               0.0.2

FROM      rwentzel/ubuntu-mono
MAINTAINER Jacques Sineriz "ssineriz@gmail.com"

# all in one script to tackle the 42 layers limit
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/prepare.sh /usr/local/bin/prepare.sh
RUN chmod +x /usr/local/bin/prepare.sh && /usr/local/bin/prepare.sh 

EXPOSE 7777

# start listener
ENTRYPOINT ["/usr/local/bin/server.sh"]