# Mono sandbox adapted for CodeWars
#
# VERSION               0.0.2

FROM      rwentzel/ubuntu-mono
MAINTAINER Jacques Sineriz "ssineriz@gmail.com"

# make sure the package repository is up to date
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

# install ucspi-tcp for tcpserver
RUN apt-get install -y ucspi-tcp

# install iptables for basic firewalling
RUN apt-get install -y iptables

# get server.sh
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/server.sh /usr/local/bin/server.sh

# get runcsharp.sh
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/container/runcsharp.sh /usr/local/bin/runcsharp.sh

# get ServiceStack.Text.dll
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/lib/ServiceStack.Text.dll /usr/local/lib/mono/4.5/ServiceStack.Text.dll

# get CodeWars.CSharp.TestFramework.dll
# this is the compiled version of https://github.com/edokan/kata-test-framework-csharp (without test units and debug code)
ADD https://github.com/ssineriz/cw-mono-sandbox/raw/master/lib/CodeWars.CSharp.TestFramework.dll /usr/local/lib/mono/4.5/CodeWars.CSharp.TestFramework.dll

# set execute permissions
RUN chmod +x /usr/local/bin/server.sh
RUN chmod +x /usr/local/bin/runcsharp.sh

# set file system permissions
RUN chmod -f o-r /* /.*
RUN chmod -f o-w /tmp

# turn off outgoing network traffic for nobody
RUN iptables -A OUTPUT -m owner --uid-owner 65534 -j DROP

# prepare home settings for nobody. Files in /.config/csharp will be loaded (or executed) before script
RUN usermod -d /home/nobody -m nobody
RUN mkdir -p /home/nobody/.config/csharp
RUN cp /usr/local/lib/mono/4.5/CodeWars.CSharp.TestFramework.dll /home/nobody/.config/csharp/

EXPOSE 7777

# start listener
ENTRYPOINT ["/usr/local/bin/server.sh"]